version: '3.7'

services:

  opensearch:
    restart: unless-stopped
    image: opensearchproject/opensearch:2.11.1
    environment:
      discovery.type: single-node
      plugins.security.disabled: true
      compatibility.override_main_response_version: true
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer

  opensearch-dashbaord:
    restart: unless-stopped
    image: opensearchproject/opensearch-dashboards:2.11.1
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]' # must be a string with no spaces when specified as an environment variable
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      opensearch:
        condition: service_started
    ports:
      - "5601:5601"